server:
  context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 800
  session:
    timeout: 6000
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  devtools:
    restart:
      exclude: static/**,jsp/**
